## The configuration of hexo-theme-plain

# Google analysis
track_id: UA-51163552-1

# The path of about page
about_url: 'http://sunaiwen.github.io/resume/dist'

# The avatar of you or your site
avatar_url: ''
