## The configuration of hexo-theme-plain

# Google analysis
trackId: UA-51163552-1

# Comment
# Type: duoshuo or disqus (disqus is not supported yet)
commentType: duoshuo

# The path of about page
about_url: '/about'