<!doctype html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="shortcut icon" href="favicon.png"/>
    <title>雅阁</title>
</head>
<body>
    <header class="head">
        <a class="homeLink" href="/">苏乃文的博客</a>
    </header>
</body>
</html>